name: Build and Push Frontend Docker Image

on:
  push:
    paths:
      - 'front-end/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          tags: nolawit/front-end:latest
          build-args: |
            APP_NAME=${{ secrets.APP_NAME }}
            SECRET_COOKIE_PASSWORD=${{ secrets.SECRET_COOKIE_PASSWORD }}
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
